version: 1.0.{build}

image: Visual Studio 2017

build:
  verbosity: detailed

cache:
  - '%LOCALAPPDATA%\\Yarn -> yarn.lock'
  - '%USERPROFILE%\.nuget\packages -> paket.lock'

artifacts:
  - path: '**\Release\*.nupkg'

build_script:
  - cmd: fake build

deploy:
  - provider: NuGet
    api_key:
      secure: dZXnErExEilbhlg+R3Pz082w/oWjVwCDiYFix0lqagA6YkwFwh8hMdTDPmEo68fS
    on:
      appveyor_repo_tag: true
